
= User uses federated commercial services which he has contracted for directly

As a User I want to buy a licence directly from a provider of data or processing services (not necessarily published on my home platform) and then access this data / service via my home platform. I also wish to directly buy compute capacity from a federated platform and perform part or all of my processing near to the data on this other platform.

In this use case the complexities of sales, billing and licensing are handled outside the federation of exploitation platforms. The user obtains a licence or a remote platform account, tied to his organisation or user ID(s), without interacting with the home platform.

The platform federation must then authorize and report his use of licensed Resources and compute resources. Involved is the User, the Licenser (copyright owner or agent authorized to issue licences), the host platform (in which the resource being accessed is originally published) and the home platform.

In this description the User is using a licensed Resource and compute facilities at a single federated platform. However, many other similar cases are possible - for example, a licensed processing service may be transferred from platform 2 to platform 3, work on data present at platform 3 and then return it to the home platform for visualization. Alternatively, only freely available or user-supplied data and processing services may be used with only compute capacity being paid for, or a remotely catalogued licensed processing service may be transferred to the home platform to run.

'''

. User discovers a commercially licensed Resource using federated search
. User contracts for the Resource licence directly from the Licenser on the licenser's web site, supplying his EP user ID(s) or an account/organization identifier
. User contracts with a federated exploitation platform, the host platform, where the data he requires is hosted, and agrees to pay for compute costs
. User accesses the resource (maybe as part of a wider processing chain) using his home platform, which may involve federated access. The user must specify that the host platform should be used for particular parts of the processing.
. User authorizes the home platform to access the User's compute resources account at the host platform.
. Any estimate presented includes the cost of licenses, of host-platform compute servers and of network transfers.
. Part of the User's processing occurs on the host platform, using data hosted there, and the result is returned to the home platform.
. The host platform authorizes his use of the Licensed Resource by making a request to an API endpoint operated by the Licenser
. Processing or data data access may be subject to re-authorization after a time or volume specified by the Licenser
. The User is billed directly for Resource use by the Licenser and compute capacity use by the host platform
. The use of the data or service is reported to the Licenser

[[aflow-home-platform-licence-use, Using the Licensed Resource on the home platform]]
.Alternative Flow: Using the Licensed Resource on the home platform

The User may buy the licence directly from the Licenser even though the processing is completed on the home platform. The Licensed Resource may need to be transferred to the home platform or may already be present.

[[aflow-host-platform-no-licence, Using a local Resource on the host platform]]
.Alternative Flow: Using a local Resource on the host platform

The User may have their own processing service or data on the home platform. This may then be transferred to the host platform, where (additional) data required for processing may be present. The User pays for the remote compute costs but no licence costs are involved.
